"""Figure 8: all-electron and GTH-LDA radial orbitals of silicon.

The curves are generated by self-consistent, spin-unpolarized, spherical
atomic Kohn--Sham calculations.  The all-electron calculation contains all
14 electrons.  The pseudopotential calculation contains the four valence
electrons and uses the bundled PyPWDFT Si GTH-PADE-q4 parameters.

The radial finite-difference solver is deliberately kept in this file so the
figure can be regenerated without importing PyPWDFT or an atomic-DFT package.
Atomic units are used throughout.
"""

import math
import os
from dataclasses import dataclass

import matplotlib.pyplot as plt
import numpy as np
from scipy.linalg import eigh_tridiagonal
from scipy.special import erf, gamma


# Si GTH-PADE-q4 (GTH-LDA-q4), as bundled with PyPWDFT.  The first and
# second rows/columns of H_S couple the two s projectors; H_P couples the
# single p projector.
GTH_SI = {
    "zion": 4.0,
    "rloc": 0.44000000,
    "cloc": np.array([-7.33610297]),
    "projector_radii": {
        0: 0.42273813,
        1: 0.48427842,
    },
    "h": {
        0: np.array([[5.90692831, -1.26189397],
                     [-1.26189397, 3.25819622]]),
        1: np.array([[2.72701346]]),
    },
}

# A basis of 80 local radial eigenstates removes the tiny spurious near-origin
# node seen with more aggressive truncations while keeping regeneration fast.
PROJECTOR_BASIS_SIZE = 80


@dataclass
class AtomicResult:
    r: np.ndarray
    orbitals: dict
    eigenvalues: dict
    iterations: int
    density_residual: float


def main():
    # A fine uniform grid resolves the compact Si 1s shell while retaining
    # enough vacuum for the neutral-atom valence tail.
    r_max = 24.0
    n_grid = 3500
    r = np.linspace(r_max / (n_grid + 1),
                    r_max * n_grid / (n_grid + 1), n_grid)

    all_electron = solve_atom(
        r,
        external_potential=-14.0 / r,
        occupations={0: [2.0, 2.0, 2.0], 1: [6.0, 2.0]},
    )
    pseudo = solve_atom(
        r,
        external_potential=gth_local_potential(r),
        occupations={0: [2.0], 1: [2.0]},
        nonlocal_projectors=gth_projectors(r),
    )

    u_1s = orient_outer_lobe(r, all_electron.orbitals[0][:, 0])
    u_2s = orient_outer_lobe(r, all_electron.orbitals[0][:, 1])
    u_3s = orient_outer_lobe(r, all_electron.orbitals[0][:, 2])
    u_ps = orient_outer_lobe(r, pseudo.orbitals[0][:, 0])

    # Eigenvectors have arbitrary signs.  Choose the signs so that the two
    # valence tails point in the same direction, then use one common scale.
    tail = (r > 1.5) & (r < 4.0)
    if np.dot(u_3s[tail], u_ps[tail]) < 0.0:
        u_ps = -u_ps

    # For an s orbital, u(r)=r R(r), so multiplying once more by r gives the
    # requested signed radial distribution r^2 R(r).  Use the same scale for
    # every curve; in particular, the all-electron and pseudo 3s amplitudes
    # remain directly comparable.
    distributions = {
        "1s": r * u_1s,
        "2s": r * u_2s,
        "3s": r * u_3s,
        "pseudo_3s": r * u_ps,
    }
    common_scale = max(
        np.max(np.abs(distributions["3s"])),
        np.max(np.abs(distributions["pseudo_3s"])),
    )
    for key in distributions:
        distributions[key] /= common_scale

    make_figure(r, distributions)

    print(
        "Si atomic LDA convergence: "
        f"all-electron {all_electron.iterations} iterations "
        f"(residual {all_electron.density_residual:.2e}), "
        f"GTH {pseudo.iterations} iterations "
        f"(residual {pseudo.density_residual:.2e})"
    )
    print(
        "3s eigenvalues [Ha]: "
        f"all-electron {all_electron.eigenvalues[0][2]:.6f}, "
        f"GTH {pseudo.eigenvalues[0][0]:.6f}"
    )
    all_electron_nodes = radial_nodes(r, u_3s)
    pseudo_nodes = radial_nodes(r, u_ps)
    print("All-electron 3s radial nodes [bohr]:", all_electron_nodes)
    print("GTH pseudo-3s radial nodes [bohr]:", pseudo_nodes)
    if len(all_electron_nodes) != 2 or len(pseudo_nodes) != 0:
        raise RuntimeError("Unexpected Si 3s radial node count")


def solve_atom(r, external_potential, occupations,
               nonlocal_projectors=None, max_iterations=160,
               mixing=0.35, tolerance=2.0e-7):
    """Solve the spherical, spin-unpolarized atomic LDA equations.

    Orbitals are represented by the reduced radial function u(r)=r R(r),
    normalized as integral |u|^2 dr = 1.  Fractional occupation of a shell
    means its density is averaged over the magnetic substates, preserving
    spherical symmetry (for Si, the open 3p shell has total occupation 2).
    """
    dr = r[1] - r[0]
    diagonal_kinetic = np.full(len(r), 1.0 / dr**2)
    off_diagonal = np.full(len(r) - 1, -0.5 / dr**2)
    electron_count = sum(sum(shells) for shells in occupations.values())

    # A smooth, normalized initial density.  Only the density is mixed; every
    # eigensystem is solved in the potential generated by that mixed density.
    decay = max(0.45, electron_count ** (1.0 / 3.0))
    density = electron_count * decay**3 * np.exp(-2.0 * decay * r) / math.pi

    residual = math.inf
    orbitals = {}
    eigenvalues = {}
    for iteration in range(1, max_iterations + 1):
        v_hartree = spherical_hartree_potential(r, density)
        v_xc = lda_vwn_potential(density)
        central_potential = external_potential + v_hartree + v_xc

        new_density = np.zeros_like(r)
        orbitals = {}
        eigenvalues = {}
        for l, shell_occupations in occupations.items():
            number_of_states = len(shell_occupations)
            diagonal = (
                diagonal_kinetic
                + central_potential
                + l * (l + 1) / (2.0 * r**2)
            )
            projectors = None
            coupling = None
            if nonlocal_projectors is not None and l in nonlocal_projectors:
                projectors, coupling = nonlocal_projectors[l]

            energies, states = lowest_radial_states(
                diagonal, off_diagonal, dr, number_of_states,
                projectors, coupling,
            )
            orbitals[l] = states
            eigenvalues[l] = energies
            for state, occupation in enumerate(shell_occupations):
                new_density += (
                    occupation * states[:, state]**2
                    / (4.0 * math.pi * r**2)
                )

        # The integrated-density residual is insensitive to the coordinate
        # singularity in n(r) at small r and has a direct electron-count scale.
        residual = math.sqrt(
            4.0 * math.pi
            * np.trapz((new_density - density)**2 * r**2, r)
            / electron_count
        )
        density = (1.0 - mixing) * density + mixing * new_density
        if residual < tolerance:
            break
    else:
        raise RuntimeError(
            f"Atomic SCF did not converge in {max_iterations} iterations; "
            f"density residual = {residual:.3e}"
        )

    # Return orbitals from the converged mixed density rather than the final
    # pre-mixing eigensystem.
    v_hartree = spherical_hartree_potential(r, density)
    central_potential = external_potential + v_hartree + lda_vwn_potential(density)
    orbitals = {}
    eigenvalues = {}
    for l, shell_occupations in occupations.items():
        diagonal = (
            diagonal_kinetic + central_potential
            + l * (l + 1) / (2.0 * r**2)
        )
        projectors = coupling = None
        if nonlocal_projectors is not None and l in nonlocal_projectors:
            projectors, coupling = nonlocal_projectors[l]
        energies, states = lowest_radial_states(
            diagonal, off_diagonal, dr, len(shell_occupations),
            projectors, coupling,
        )
        orbitals[l] = states
        eigenvalues[l] = energies

    return AtomicResult(r, orbitals, eigenvalues, iteration, residual)


def lowest_radial_states(diagonal, off_diagonal, dr, number_of_states,
                         projectors=None, coupling=None):
    """Return the lowest eigenpairs of a local or separable radial operator."""
    if projectors is None:
        energies, states = eigh_tridiagonal(
            diagonal,
            off_diagonal,
            select="i",
            select_range=(0, number_of_states - 1),
            check_finite=False,
            lapack_driver="stebz",
        )
    else:
        # The GTH correction has rank two for Si s and rank one for Si p.
        # Represent it in a generous low-energy eigenbasis of the local radial
        # Hamiltonian.  This avoids slow iterative convergence against the
        # enormous top of a fine-grid finite-difference spectrum.
        basis_size = min(PROJECTOR_BASIS_SIZE, len(diagonal) - 1)
        local_energies, basis = eigh_tridiagonal(
            diagonal,
            off_diagonal,
            select="i",
            select_range=(0, basis_size - 1),
            check_finite=False,
            lapack_driver="stebz",
        )
        basis /= math.sqrt(dr)
        overlaps = projectors.T @ basis * dr
        projected_hamiltonian = (
            np.diag(local_energies) + overlaps.T @ coupling @ overlaps
        )
        projected_energies, coefficients = np.linalg.eigh(
            projected_hamiltonian
        )
        energies = projected_energies[:number_of_states]
        states = basis @ coefficients[:, :number_of_states]

    # LAPACK/ARPACK normalize with a Euclidean sum; radial normalization
    # contains the grid spacing.
    states /= np.sqrt(np.sum(states**2, axis=0) * dr)
    return energies, states


def spherical_hartree_potential(r, density):
    """Electrostatic potential of a spherical electron density."""
    radial_charge = 4.0 * math.pi * density * r**2
    enclosed = cumulative_trapezoid(radial_charge, r)
    outer_integrand = 4.0 * math.pi * density * r
    outer = cumulative_trapezoid(outer_integrand[::-1], r[::-1])[::-1]
    # cumulative_trapezoid on a decreasing grid carries a minus sign.
    return enclosed / r - outer


def cumulative_trapezoid(values, coordinates):
    result = np.zeros_like(values)
    result[1:] = np.cumsum(
        0.5 * (values[1:] + values[:-1]) * np.diff(coordinates)
    )
    return result


def lda_vwn_potential(density):
    """Slater exchange plus VWN5 correlation, matching PyPWDFT's LDA."""
    rho = np.maximum(np.asarray(density, dtype=float), 1.0e-18)
    rs = (3.0 / (4.0 * math.pi * rho)) ** (1.0 / 3.0)

    exchange_energy = (
        -0.75 * (3.0 / (2.0 * math.pi)) ** (2.0 / 3.0) / rs
    )
    exchange_potential = 4.0 * exchange_energy / 3.0

    # VWN5 fit to the Ceperley--Alder electron gas.  A is tabulated in
    # Rydberg; the factors below produce Hartree, as in PyPWDFT.
    a = 0.0621814
    x0 = -0.10498
    b = 3.72744
    c = 12.9352
    x = np.sqrt(rs)
    polynomial = x**2 + b * x + c
    polynomial_x0 = x0**2 + b * x0 + c
    f_x0 = b * x0 / polynomial_x0
    t = 2.0 * x + b
    q = math.sqrt(4.0 * c - b**2)
    angle = np.arctan(q / t)
    correlation_energy = a / 2.0 * (
        np.log(x**2 / polynomial)
        + 2.0 * b / q * angle
        - b * x0 / polynomial_x0
        * (np.log((x - x0)**2 / polynomial)
           + 2.0 * (b + 2.0 * x0) / q * angle)
    )
    correlation_potential = correlation_energy - x * a / 12.0 * (
        2.0 / x - t / polynomial - 4.0 * b / (t**2 + q**2)
        - f_x0 * (
            2.0 / (x - x0) - t / polynomial
            - 4.0 * (2.0 * x0 + b) / (t**2 + q**2)
        )
    )
    return exchange_potential + correlation_potential


def gth_local_potential(r):
    """Real-space local part of the Si GTH-PADE-q4 potential."""
    rloc = GTH_SI["rloc"]
    scaled_r2 = (r / rloc)**2
    polynomial = np.zeros_like(r)
    for index, coefficient in enumerate(GTH_SI["cloc"]):
        polynomial += coefficient * scaled_r2**index
    return (
        -GTH_SI["zion"] / r * erf(r / (math.sqrt(2.0) * rloc))
        + np.exp(-0.5 * scaled_r2) * polynomial
    )


def gth_projectors(r):
    """Normalized real-space GTH radial projectors q_i(r)=r p_i(r)."""
    result = {}
    for l, coupling in GTH_SI["h"].items():
        radius = GTH_SI["projector_radii"][l]
        columns = []
        for projector_index in range(1, coupling.shape[0] + 1):
            power = l + 2 * (projector_index - 1)
            gamma_argument = l + (4 * projector_index - 1) / 2.0
            normalization = (
                math.sqrt(2.0)
                / (radius**(l + (4 * projector_index - 1) / 2.0)
                   * math.sqrt(gamma(gamma_argument)))
            )
            radial_projector = (
                normalization * r**power
                * np.exp(-0.5 * (r / radius)**2)
            )
            columns.append(r * radial_projector)
        result[l] = (np.column_stack(columns), coupling)
    return result


def radial_nodes(r, radial_function, cutoff=1.5):
    """Locate sign-changing nodes before cutoff by linear interpolation."""
    inside = r < cutoff
    positions = []
    for index in np.flatnonzero(
            np.signbit(radial_function[inside][:-1])
            != np.signbit(radial_function[inside][1:])):
        x0, x1 = r[index], r[index + 1]
        y0, y1 = radial_function[index], radial_function[index + 1]
        positions.append(x0 - y0 * (x1 - x0) / (y1 - y0))
    return np.array(positions)


def orient_outer_lobe(r, radial_function):
    """Choose the arbitrary eigenvector sign so its largest r*u lobe is positive."""
    distribution = r * radial_function
    sign = np.sign(distribution[np.argmax(np.abs(distribution))])
    return radial_function if sign >= 0.0 else -radial_function


def make_figure(r, distributions):
    fig, axis = plt.subplots(1, 1, dpi=144, figsize=(6, 3))
    cyan = "#00b9f2"
    axis.axhline(0.0, color="black", linewidth=0.7)
    axis.plot(
        r, distributions["1s"], color="black", linewidth=1.0,
        linestyle=":", label="all-electron Si 1s", alpha=0.5
    )
    axis.plot(
        r, distributions["2s"], color="black", linewidth=1.0,
        linestyle="-.", label="all-electron Si 2s", alpha=0.5
    )
    axis.plot(
        r, distributions["3s"], color="black", linewidth=1.2,
        linestyle="--", label="all-electron Si 3s",
    )
    axis.plot(
        r, distributions["pseudo_3s"], color=cyan, linewidth=1.8,
        label="GTH pseudo-3s",
    )
    axis.grid(linestyle="--", linewidth=0.4, alpha=0.5)
    axis.set_xlim(0.0, 6.0)
    axis.set_ylim(-0.2, 1.1)
    axis.set_xlabel(r"distance from nucleus $r$ [a.u.]")
    axis.set_ylabel(
        r"radial distribution function $r^2\psi(r)$"
    )
    axis.set_title("Self-consistent atomic Si s orbitals and GTH pseudo-3s")
    axis.legend(loc="upper right", fontsize=8)
    output = os.path.join(
        os.path.dirname(__file__), "..", "img", "fig8_pseudo_orbital.pdf"
    )
    fig.tight_layout()
    fig.savefig(output)
    plt.close(fig)


if __name__ == "__main__":
    main()
