name: build

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - develop
    tags:
      - "v**"
  release:
    types:
      - published

jobs:
  create-release:
    runs-on: ubuntu-latest
    permissions: write-all
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
    - name: Create Release
      id: create_release
      uses: ncipollo/release-action@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        name: Release ${{ github.ref_name }}
        draft: false
        prerelease: false
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}

  build-latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Insert GIT id
        run: sed -e "s/\\\lfoot{}/\\\lfoot{git id: $GITHUB_SHA}/" main.tex
      - name: Compile LaTeX
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
          texlive_version: 2024
      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: PDF
          path: main.pdf
      - name: Produce front page
        run: |
          sudo apt update && sudo apt install poppler-utils
          pdftoppm -jpeg -r 150 -f 1 -l 1 main.pdf pwdft-filot
          mv -v pwdft-filot-01.jpg pwdft-filot-frontpage.jpg
      - name: Upload IMG file
        uses: actions/upload-artifact@v4
        with:
          name: IMG
          path: pwdft-filot-frontpage.jpg

  deploy-pdf:
    runs-on: ubuntu-latest
    needs: [build-latex,create-release]
    permissions: write-all
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
    - name: Download PDF
      uses: actions/download-artifact@v4
      with:
        name: PDF
        path: ./
    - name: Change name
      run: |
        mv main.pdf pwdft-filot.pdf
    - name: Upload Release Asset
      id: upload-release-asset-launcher
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ needs.create-release.outputs.upload_url }}
        asset_path: pwdft-filot.pdf
        asset_name: pwdft-filot.pdf
        asset_content_type: application/pdf

  deploy-img:
    runs-on: ubuntu-latest
    needs: [build-latex,create-release]
    permissions: write-all
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
    - name: Download IMG
      uses: actions/download-artifact@v4
      with:
        name: IMG
        path: ./
    - name: Upload Release Asset
      id: upload-release-asset-launcher
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ needs.create-release.outputs.upload_url }}
        asset_path: pwdft-filot-frontpage.jpg
        asset_name: pwdft-filot-frontpage.jpg
        asset_content_type: image/jpeg